Add check if @rumblefishdev/ui is installed

diff --git a/.github/workflows/deploy-stage.yml b/.github/workflows/deploy-stage.yml
--- a/.github/workflows/deploy-stage.yml
+++ b/.github/workflows/deploy-stage.yml
@@ -48,10 +48,17 @@ jobs:
       - name: Install dependencies
         run: |
           npm i
-          npm install @rumblefishdev/ui
           node_modules/.bin/lerna bootstrap
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+
+      - name: Check if @rumblefishdev/ui installed
+        run: |
+          if [[ ! -d packages/frontend/node_modules/@rumblefishdev/ui ]]; then
+            echo "Error: @rumblefishdev/ui not installed"
+            exit 1
+          fi
 
       - name: ls frontend modules
         run: |
